PROJECT_PATH = 'C:\\Users\\gary\\Desktop\\RansomRadar'

RAW_ROOT_PATH = f'{PROJECT_PATH}\\dataset\\raw'
HPC_ROOT_path = f'{PROJECT_PATH}\\dataset\\hpcdata'
IRP_ROOT_PATH = f'{PROJECT_PATH}\\dataset\\irplog'
PARSER_PATH = f'{PROJECT_PATH}\\helper\\PARSER\\PARSER\\bin\\Release\\PARSER.exe'
PARSER_PROFILE_PATH = f'{PROJECT_PATH}\\helper\\parse.wpaProfile'
FEATURE_PATH = f'{PROJECT_PATH}\\features'
RESULT_PATH = f'{PROJECT_PATH}\\result'
MODEL_PATH = f'{PROJECT_PATH}\\models'